### ISSUE TITLE
Stat Component

### ISSUE THREAD

**Issue by darenkeck** [Margorah/CharSheetNg2#1]
Complete initial pass the stat component
- Define the model for what is stored in a stat
- UI for both edit and normal mode, including the logic to switch between the two

**Comment by darenkeck** [comment]
Defined a stat interface and setup component as a 'dumb' component with data flowing in, and changes flowing out to a container component. We need to nail down what all we want editable in edit mode though.

**Comment by Margorah** [comment]
Should there be two components in the StatsViewComponent? One that is just a view and the other that is the editable form? We could then use an nested ngIf inside the ngFor that is a view toggle. I remember that being basically what I did in the Angular1 version

**Comment by Margorah** [comment]
The move to Ionic invalidates this concern
