### ISSUE TITLE
Data Handling in Services

### ISSUE THREAD

**Issue by Margorah** [Margorah/CharSheetNg2#2]
Should all of the data end of this app be managed by some amount of services? That was how the Angular 1 version handled data. It would make it easier to test with dummy data then add in talking the server when are ready for that

**Comment by darenkeck** [comment]
Yeah, I definitely agree about moving the state stuff for this app to a service. I was thinking about moving this to use ngrx/store - which would have a nice way of delivering the array of stats for a given character, or any other state information for the app.

Using ngrx/store would move the current shoehorned in dummy data from this:
```typescript
     // for now using a dummy list    
    let dummyStats:Array<Stat> = [
      {name: 'shield', value: 70, maximum: 100, type: 'health'},
      {name: 'sword', value: 60, maximum: 100, type: 'weapon'}
    ];

    this.stats = Observable.create(observer => {
      // emit dummy data
      // this will be fetched from an http request eventually
      observer.next(dummyStats);
    });
```

to something like this:
```typescript
// send request to server to fetch the stats for the given character name
// the http service will then handle the response, adding items to the store
// this could even be done in the charlist page before navigating
this._http.get(this.name)

// this.stats is already an observable, so it will watch for a response from store. When the http service
// adds entries, our observable will get the update list of values.
this.stats = this._store.get_character_stats(this.name); // or some other method
```

This will make it at least initially more complicated, but I think once I have the pattern in place with ngrx/store I can describe what is going on. It is a really nice way to manage state.

**Comment by darenkeck** [comment]
I'm closing this and creating a separate issue for incorporating ngrx/store.
