### ISSUE TITLE
Use https in api server

### ISSUE THREAD

**Issue by darenkeck** [Margorah/CharSheetNg2#43]
Using this blog post for reference: http://blog.mgechev.com/2014/02/19/create-https-tls-ssl-application-with-express-nodejs/

**Comment by darenkeck** [comment]
and this post for generating certificates: https://devcenter.heroku.com/articles/ssl-certificate-self

**Comment by darenkeck** [comment]
To ignore self-signed certificates, we might need this:

https://forum.ionicframework.com/t/https-connection-with-self-signed-certificate/12974

This allowed me to pin a self-signed certificate and make https api requests.

**Comment by Margorah** [comment]
Online functionality on hold for a different release version, closing until then.
