### ISSUE TITLE
Use input type="submit" for all forms to help iOS 'go' button

### ISSUE THREAD

**Issue by darenkeck** [Margorah/CharSheetNg2#44]
The iOS 'go' method is dependent on an element `<input type="submit">` being present to actually submit a form. [reference on SO](https://stackoverflow.com/questions/5665203/getting-iphone-go-button-to-submit-form).

We should review each form and make sure the submit approach uses this and also plays nicely with angular forms.

**Comment by Margorah** [comment]
623d80a1d761a12b64eaa56dd1095347479f9924

Does this solution work on iOS devices?

**Comment by darenkeck** [comment]
Ok, I verified that this does in fact work!

Apologies, I did not see your commit. Next time please go right ahead and commit on the feature branch. I'll continue work on this Sunday and I'll cherry-pick commit 623d80a. I think the changes should be pretty quick!
