### ISSUE TITLE
Initial server setup

### ISSUE THREAD

**Issue by darenkeck** [Margorah/CharSheetNg2#7]
Create ./server folder, and setup node server and startup scripts to serve from ./dist folder.

**Comment by Margorah** [comment]
What do you mean by server from dist folder? I added a new package.json in the /server directory and was running node from there. Figured it might be relevant if we want to install server specific dependencies and devDependencies. We could always move the server to its own repo

**Comment by darenkeck** [comment]
> What do you mean by server from dist folder?

By this I just meant serve the output javascript files generated by angular-cli.

> We could always move the server to its own repo

Nice. Yeah, I think moving the server in its on repo makes sense.

**Comment by Margorah** [comment]
When I figure out how/if it can combine it with the backend of other projects I'll move it then

**Comment by Margorah** [comment]
Decided to leave it for now. If it changes will make note
